### PR TITLE
Replace blurry images for all project stories

### PR DESCRIPTION
**Pull request by tlfrd**

### CODE REVIEW

**Comment by h-lame** [comment]
With this change it doesn't look like there's a difference between the image and the 2x variant any more, which doesn't seem like the correct approach.

**Comment by tlfrd** [comment]
@mybits seemed to suggest that this was okay to do. Although I agree that is not a good approach (and was more of a temporary solution). The blurry images problem only seems to be a problem on non retina devices (where the screen size is large). The possible solutions I can think of would be to make all images higher resolution or to reduce the definition of retina. @h-lame what do you suggest?

**Comment by h-lame** [comment]
@tlfrd TBH I'm not sure.  No need to reduce quality on the non-2x versions just so the 2x versions appear "legit".  But then, if there's no difference between the 2x and non-2x versions why bother with the 2x versions at all?  Should make the markup simpler.  Of course, if there is no difference between the 2x versions and the non-2x versions there's an argument that our visitors with retina screens aren't getting the sharpest image they can get, and so we should be making the 2x ones even bigger.  (e.g. if the non-2x versions are now 700px wide the 2x versions should be 1400px wide).

But! I'm not sure these images are ever shown at 700px wide so it's probably worth checking what the widest they are shown at is, and optimizing for that.  Then we can do a 2x version at that width.  We should also make sure we're using the best possible resize alogrithm in whatever tool we're using and seeing if a sharpen effect needs to be applied to the smallest version to avoid blur.  Also working from the largest possible source image will help.

**Comment by h-lame** [comment]
> and optimizing for that. Then we can do a 2x version at that width

This isn't clear, sorry. What I mean is the non-2x version should be `w` px wide, where `w` is the maximum width our design uses, and the 2x version should be `2 * w` px wide.

**Comment by tomsabin** [comment]
@tlfrd The largest a single tile image will be is 480px (that’s the maximum single column width) - that’s for both the single column and two column layouts. there are a number of square images that are 350px wide so it’s likely there are the blurry ones that need replacing. That'll be 480px width for non-retina, and 960px wide for retina.

However, for the two-column images (the header images for example), are correct at 960px for non-retina displays. I doubt there will be much benefit of providing a larger (in file size and dimension) image for the browser to resize back down to 960px (the maximum container width), but as Murray already touched on, perhaps we can improve the export settings to make it seem sharper, but still reducing file size to a minimum.

Also, should this be a PR to staging?

**Comment by tomsabin** [comment]
Here's a screenshot of the single column mobile view at 480px - which is upscaling the image from 350px.

screen shot 2016-04-11 at 21 38 08

**Comment by tomsabin** [comment]
And the desktop container at 960px (image already at 960px for non-retina):

screen shot 2016-04-11 at 21 39 22

**Comment by tomsabin** [comment]
Also, to test non-retina images on Chrome with a retina display, you can add a new device and set the pixel ratio to 1:

screen shot 2016-04-11 at 21 41 54

**Comment by tlfrd** [comment]
Yes this was meant to be to staging, I've made this mistake a few times this week. Thanks for the Chrome tip.

**Comment by tlfrd** [comment]
@tomsabin so should the normal (non-2x) image should have a width of 480px and the 2x image a width of 960px from now on?

**Comment by tomsabin** [comment]
@tlfrd yes, that seems correct to me

**Pull request closed without merging**
