### PR TITLE
Add Bucks CC project story

### PR DESCRIPTION
**Pull request by tlfrd**
PT: https://www.pivotaltracker.com/n/projects/1364344

### CODE REVIEW

**Comment by FriedSock** [comment]
LGTM

**Comment by tomsabin** [comment]
Was this meant to go into production? There are a few things which I've spotted on https://unboxed.co/project-stories/bucks-cc

Text is too long for the first tile, leaving a white gap underneath the image:
screen shot 2016-04-07 at 17 04 24

Same issue on the "MVP prototyping using user feedback" section:
screen shot 2016-04-07 at 17 05 37

And Leon's caricature looks small in comparison to the rest of the team:
screen shot 2016-04-07 at 17 06 22

**Comment by FriedSock** [comment]
Oh goddamit! The PR was made against production by mistake, my bad for not checking it.

**Comment by tlfrd** [comment]
Is the only solution to the white gap issue reducing the amount of text? I've seen the same issue with a few other project stories?

**Comment by tomsabin** [comment]
@tlfrd The solution we've been going with in the past is to reduce the text, yep. Another solution is to remove the bottom padding of the `.text-tile` so that there is a little bit of an overflow in case it happens. I'd recommend making that change, but it's still worth visually testing the responsiveness of the site.

**Pull request merged**
