### PR TITLE
Developer process page

### PR DESCRIPTION
**Pull request by mybits**
PT: https://www.pivotaltracker.com/story/show/139366619

### CODE REVIEW

**Comment by mybits** [comment]
It will be posted as a blog post instead of a separate page

**Comment by h-lame** [comment]
Having it as a blog post seems a bit strange.  A first class page that doesn't live under `/blog` will be slightly shorter and make it seem more "official" than "oh that's a blog post, maybe it's not the most uptodate version of how they do things"

**Comment by mybits** [comment]
I think the idea is to link to the blog post at a developer job advert page. But I agree (I think it was already discussed) that we should consider having a 'handbook' pdf available somewhere.

**Comment by h-lame** [comment]
Let's push back on this being a blog post - it's all just html at the moment so there's no strong difference in how we build it.

**Pull request closed without merging**
