### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by tomsabin**
This PR also updates the project story index page so that we don't have duplicate "featured" project story images - instead we can share these images across to the homepage.

### CODE REVIEW

**Comment by mybits** [comment]
Just a reminder to change Martyn's image to 120px high for mobile

**Comment by mybits** [comment]
:+1:

**Comment by tomsabin** [comment]
Mobile version of "Contact Martyn" section in https://github.com/unboxed/ubxd_web_refresh/commit/d8d582d017daa65fa7939cbc5afd719832ee2af9

**Comment by mybits** [comment]
Awesome :ship: it

**Pull request merged**
