### PR TITLE
Blog author and date to be lowercase in blog article

### PR DESCRIPTION
**Pull request by mybits**

### CODE REVIEW

**Comment by GraemeMcCubbin** [comment]
There's an inconsistency with names and dates on blog tiles vs. blog post pages, lower case vs. normal case. I remember the specification being lower case names wherever possible, which now includes the People page.

**Comment by mybits** [comment]
I'm gonna merge it unless we want to discuss it more?

**Comment by GraemeMcCubbin** [comment]
I'd say merge and we can discuss the overall lower/standard case topic afterwards.

**Comment by mybits** [comment]
:+1:

**Pull request merged**
