### PR TITLE
Add transition to homepage service buttons

### PR DESCRIPTION
**Pull request by DennisTsiang**

### CODE REVIEW

**Review by elenatanasoiu — APPROVED** [review]

**Comment by DennisTsiang** [comment]
Story has been changed to add transition to all buttons in the site

**Comment by neilvanbeinum** [comment]
Do we also want to add the transition to the whitepaper 'download' buttons too?

**Comment by DennisTsiang** [comment]
Yes we do Neil, good spot. I've add that too now

**Comment by DennisTsiang** [comment]
Discussed with Neil in person, and he approved it

**Pull request merged**
