### PR TITLE
People index

### PR DESCRIPTION
**Pull request by tomsabin**
Problems to solve:
- nested links (e.g. tile link, but also email & social networks)
- caricature images need to be aligned to top (i.e. without whitespace). However, this would then need fixing in the blog author section of an article

### CODE REVIEW

**Comment by mybits** [comment]
Hi @FriedSock - I've changed those too small caricatures so we won't be forced to use different styling on them. 
If that's all right then all the other things LGTM

**Comment by h-lame** [comment]
I don't really understand why the images need changing but there are some issues with the changed ones:

They're noticeably more blurry even though they're roughly the same size (perhaps there is an original that is larger we could use for the resizing?) and some of the transparency / white background stuff isn't the same (e.g. Willa's trousers are now transparent when they were white and the "hole" formed by the arms bending back up to the body used to be transparent, but is now white).

**Comment by mybits** [comment]
hi @h-lame the thing is most of the caricatures are completely different, some of them have large heads, and some are tiny. So we're trying to make them look more or less the same on the people index page. 
You're right the one that I uploaded became blurry, not sure why as I've rescaled images from quite big originals. I will try to fix them.

**Comment by mybits** [comment]
So images are changed. No blurriness, trousers back to white: 79bd5a5
All of these caricatures need some love, but I don't think we'd like to spend so much time in front of Gimp (as for me), so it might be a job for a designer when available.

**Comment by FriedSock** [comment]
A signature has appeared at the bottom of Carrie's one :pencil2: 

I was worried about the effect on the blog pages, but it seems out of the two, only Carrie has authored one blog post. She looks like she is floating a bit, but its not really noticeable.

screen shot 2016-01-15 at 13 54 47

**Comment by FriedSock** [comment]
Willa still looks quite a bit smaller than everyone else, but I think this is as good as it will get without cropping her, or adding a styling exception for her image.

screen shot 2016-01-15 at 14 13 07

**Comment by h-lame** [comment]
How are we cropping those images?  Is it just done in the browser with z-indexes and such? 'cos we're showing more of Willa's body than anyone else.  Maybe we'd get better results if we hand-crafted optimised cropped images for these tiles.

**Comment by mybits** [comment]
They are just different caricatures @h-lame - the caricaturists were making them in all different sizes. Take a look at Anson's and Sarah's for that example. We would have to change all of them so they would fit one pattern.

**Comment by mybits** [comment]
@FriedSock - signature removed :) I agree Willa is still smaller, but she's not smaller than Claire's for that matter. So at least we want to change all of them, I'd say we're ready for merge.

**Comment by h-lame** [comment]
On the old site we had a "headshot" image that was manually cropped to the right size so that folks heads were mostly the same size, and then the full head+body caricature.  It doesn't matter if some of the full caricatures have big heads and other's small because you never see them next to each other.  We could keep the separate, manually cropped image.  Seems on this new tile layout we're only using the full head+body caricature and scaling / cropping in the browser, which is always going to give us wonky results.

**Comment by mybits** [comment]
You're right. We should probably use different images in people-index page (headshots only). I'll create a separate story for that as that's a bunch of changes. Thanks for pointing that out!

**Comment by FriedSock** [comment]
I'm not sure why we are using the full body images opposed to the headshots that were on the old site. I presumed it was a deliberate decision, maybe not? It might have been so we were showing the same image that would open up when you viewed each individual person page, but they are gone now.

**Comment by mybits** [comment]
Yes, the decision was to use full body images on the blog posts.

**Pull request merged**
