### PR TITLE
Implement wider layout

### PR DESCRIPTION
**Pull request by cdccollins**

### CODE REVIEW

**Comment by ubxd** [comment]
Deploy preview for *unboxed-co-production* ready!

Built with commit bf7effde9c5e3530a56c75482fa95ecdb67fcb34

https://deploy-preview-533--unboxed-co-production.netlify.com

**Review by h-lame — APPROVED** [review]
I like the ambition of the PR title 😉.  I think the real test of this is likely to be in the deployed version, and probably warrants a designers eye so I'm just approving this on general merit.

My only minor thought is that we could rebase away the 1st "WIP - ..." commit as we basically fix the WIPpyness of it in the next commit, so why not pretend to our future biographers that we got it right first time around?

**Review by h-lame — APPROVED** [review]
I'm not 100% convinced by the result - the menu text on desktop seems quite small, but I also assume that this is intentional as these commits were originally authored by @borisdivjak.  The actual code seems legit.  It's hard to tell from the commits but we might get warnings from google about the size of the images - did we run them through `jpgoptim` or `pngcrush` or whatever to make sure we got the smallest possible size for the resolution and quality we want?  (We can do this later though once we get results from google).

**Comment by cdccollins** [comment]
@h-lame This is kind of still a WIP. We still need a conversation about text size etc. All the images have been run through imageoptim (several times), but yeah we can see what google says.

**Comment by h-lame** [comment]
@cdccollins ah, fair enough.  Maybe we could flag this PR with [WIP] or whatever in the title until we're ready?

**Comment by h-lame** [comment]
:+1: on the `imageoptim` though.  Good stuff!

**Review by h-lame — APPROVED** [review]
Do it!

**Pull request merged**
