### PR TITLE
Add Ben Baumann to people page

### PR DESCRIPTION
**Pull request by cdccollins**

### CODE REVIEW

**Review by h-lame — COMMENTED** [review]
Ben looks a bit blurry, do we have a sharper version of his caricature?

**Comment by ubxd** [comment]
Deploy preview for *unboxed-co-production* ready!

Built with commit d26f5d6065639ef6a76dd82a002634650230d393

https://deploy-preview-527--unboxed-co-production.netlify.com

**Comment by cdccollins** [comment]
I did some resizing and I think it got blurred on the way, I'll retry it.

**Comment by benbaumann95** [comment]
Looks good, thanks Celia. After 5 months i have made it at last...

**Review by h-lame — APPROVED** [review]

**Pull request merged**
