### PR TITLE
Add Vinul Wimalaweera to people page

### PR DESCRIPTION
**Pull request by vinulw**

### CODE REVIEW

**Comment by h-lame** [comment]
Hi @VinDel77 - the image needs to be cropped closer to the caricature so it won't go wonky when displayed next to others.  We also need to reduce the file size as it's 2.5Mb!  Most of the other images are 212x425 and < 100k.  Once you resize see what the file size is; if it's still high talk to @NeilvB who ran some image optimisation recently (see: #329)

**Comment by h-lame** [comment]
Might be worth adding some docs about these sizes as you're not the first person to do this!  Maybe we should write an image processor to sit in the build process to transform the assets from <whatever size> to the correct size and run the optimisation thing.

**Comment by vinulw** [comment]
@h-lame thank you for the spot. I accidentally uploaded the wrong file. @NeilvB gave me instructions on resizing and cropping the images were fairly clear and easy to follow. These may be worth adding to the docs as you suggested to make it a bit clearer for anyone new.

**Comment by neilvanbeinum** [comment]
This looks good 👍  @VinDel77 and I agreed that I'd update the README to include caricature instructions as part of a separate PR https://github.com/unboxed/unboxed.co/pull/338

**Pull request merged**
